version: '2'
services:
  processor-last-file:
    build: .
    image: keboola/processor-last-file
    tty: true
    stdin_open: true
    volumes:
      - ./:/code
  processor-last-file-tests:
    image: keboola/processor-last-file
    entrypoint: bash -c "composer install && php vendor/bin/phpunit"
    volumes:
      - ./:/code
